FROM workbench-images:cuda-c9s-py311-runtime-cudnn_2023c_20230922

LABEL name="workbench-images:cuda-runtime-datascience-c9s-py311_2023c_20230922" \
    summary="cuda-runtime-datascience  image with Python py311 based on c9s" \
    description="cuda-runtime-datascience  image with Python py311 based on c9s" \
    io.k8s.description="cuda-runtime-datascience  image  with Python py311 based on c9s for ODH or RHODS" \
    io.k8s.display-name="cuda-runtime-datascience  image  with Python py311 based on c9s" \
    authoritative-source-url="https://github.com/opendatahub-contrib/workbench-images" \
    io.openshift.build.commit.ref="2023c" \
    io.openshift.build.source-location="https://github.com/opendatahub-contrib/workbench-images" \
    io.openshift.build.image="https://quay.io/opendatahub-contrib/workbench-images:cuda-runtime-datascience-c9s-py311_2023c_20230922"

##########################
# Deploy Python packages #
##########################

USER 1001

WORKDIR /opt/app-root/bin/

# Copy packages list
COPY --chown=1001:0 requirements.txt ./

# Install packages and cleanup
# (all commands are chained to minimize layer size)
RUN echo "Installing softwares and packages" && \
    # Install Python packages \
    pip install --no-cache-dir -r requirements.txt && \
    # Fix permissions to support pip in Openshift environments \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

WORKDIR /opt/app-root/src/

##########################

###########################
# Deploy Runtime packages #
###########################

USER 1001

WORKDIR /opt/app-root/bin

# Copy notebook launcher and utils
COPY --chown=1001:0 utils utils/

WORKDIR /opt/app-root/src


