apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
  name: code-server
  namespace: opendatahub
  labels:
    app: code-server
spec:
  template:
    spec:
      containers:
        - env: []
          name: code-server
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          serviceAccountName: default
          image: quay.io/opendatahub-contrib/workbench-images:code-server-ubi9-py39_2023a_latest
          workingDir: /opt/app-root/src