#!/bin/bash

set -eo pipefail

set -x

# Generate htdigest password file for webdav access if it doesn't exist.

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    DEPLOYMENT=`echo $HOSTNAME | sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'`
    NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`
fi

# Pre-clone repositories defined in JUPYTER_PRELOAD_REPOS
if [ -n "${JUPYTER_PRELOAD_REPOS}" ]; then
    for repo in `echo ${JUPYTER_PRELOAD_REPOS} | tr ',' ' '`; do
        # Check for the presence of "@branch" in the repo string
        REPO_BRANCH=$(echo ${repo} | cut -s -d'@' -f2)
        if [[ -n ${REPO_BRANCH} ]]; then
          # Remove the branch from the repo string and convert REPO_BRANCH to git clone arg
          repo=$(echo ${repo} | cut -d'@' -f1)
          REPO_BRANCH="-b ${REPO_BRANCH}"
        fi
        echo "Checking if repository $repo exists locally"
        REPO_DIR=$(basename ${repo})
        if [ -d "${REPO_DIR}" ]; then
            pushd ${REPO_DIR}
            GIT_SSL_NO_VERIFY=true git pull --ff-only
            popd
        else
            GIT_SSL_NO_VERIFY=true git clone ${repo} ${REPO_DIR} ${REPO_BRANCH}
        fi
    done
fi

# Start the Jupyter notebook instance.

. /opt/app-root/bin/start-notebook.sh "$@"
