ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# CuDNN
# --------

ENV NV_CUDNN_VERSION 8.9.0.131-1
ENV NV_CUDNN_PACKAGE libcudnn8-${NV_CUDNN_VERSION}.cuda11.8

LABEL com.nvidia.cudnn.version="${NV_CUDNN_VERSION}"

USER 0

RUN yum install -y \
    ${NV_CUDNN_PACKAGE} \
    && yum -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf && \
    find /var/log -type f -name "*.log" -exec rm -f {} \;

USER 1001