ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# CUDA Devel
# ----------

ENV NV_CUDA_LIB_VERSION 11.8.0-1
ENV NV_NVPROF_VERSION 11.8.87-1
ENV NV_NVPROF_DEV_PACKAGE cuda-nvprof-11-8-${NV_NVPROF_VERSION}
ENV NV_CUDA_CUDART_DEV_VERSION 11.8.89-1
ENV NV_NVML_DEV_VERSION 11.8.86-1
ENV NV_LIBCUBLAS_DEV_VERSION 11.11.3.6-1
ENV NV_LIBNPP_DEV_VERSION 11.8.0.86-1
ENV NV_LIBNPP_DEV_PACKAGE libnpp-devel-11-8-${NV_LIBNPP_DEV_VERSION}
ENV NV_LIBNCCL_DEV_PACKAGE_NAME libnccl-devel
ENV NV_LIBNCCL_DEV_PACKAGE_VERSION 2.15.5-1
ENV NCCL_VERSION 2.15.5
ENV NV_LIBNCCL_DEV_PACKAGE ${NV_LIBNCCL_DEV_PACKAGE_NAME}-${NV_LIBNCCL_DEV_PACKAGE_VERSION}+cuda11.8

USER 0

# Install toolkit and other devel packages
RUN yum install -y \
    make \
    cuda-toolkit-11-8 \
    cuda-command-line-tools-11-8-${NV_CUDA_LIB_VERSION} \
    cuda-libraries-devel-11-8-${NV_CUDA_LIB_VERSION} \
    cuda-minimal-build-11-8-${NV_CUDA_LIB_VERSION} \
    cuda-cudart-devel-11-8-${NV_CUDA_CUDART_DEV_VERSION} \
    ${NV_NVPROF_DEV_PACKAGE} \
    cuda-nvml-devel-11-8-${NV_NVML_DEV_VERSION} \
    libcublas-devel-11-8-${NV_LIBCUBLAS_DEV_VERSION} \
    ${NV_LIBNPP_DEV_PACKAGE} \
    ${NV_LIBNCCL_DEV_PACKAGE} \
    && yum -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf && \
    find /var/log -type f -name "*.log" -exec rm -f {} \;

ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs

USER 1001